name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: maximousblk/setup-deno@v2.0.0
        with:
          deno-version:: ^1.34.3

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "sweet-crab-66"
          entrypoint: "main.ts" # 📝 Update the entrypoint
          root: "."
